# src/builder/build_config.yaml
# Define los pasos de construcción y el orden de ejecución para el proyecto pc3-grupo4-tema3.

# Configuración global
global_settings:
  terraform_command: "terraform" # Puedes cambiarlo a 'tofu' si usas OpenTofu
  auto_approve: true       # Si es true, añade -auto-approve a los comandos apply y destroy

# Pasos de la construcción. Se ejecutarán en el orden en que aparecen.
build_steps:
  - name: "01-deploy-builder-pattern"
    description: "Despliega la infraestructura usando el patrón Builder (este mismo módulo)."
    directory: "."             # Ruta relativa desde src/builder/ 
    action: "apply"
    variables:
      step1_initialize_env_enabled: true
      step1_config:
        name: "ProductionBase"
        type: "HighAvailability"
      step2_configure_network_enabled: true
      step2_config:
        cidr_block: "10.100.0.0/16"
        subnet_count: "3"
      step3_deploy_app_enabled: true
      step3_config:
        app_name: "CriticalService"
        app_version: "v2.0.0"

  - name: "02-deploy-factory-pattern"
    description: "Despliega recursos usando el patrón Factory."
    directory: "../factory"    # Ruta relativa desde src/builder/
    action: "apply"
    variables:
      resource_type: "database_instance"
      product_count: 2

  - name: "03-deploy-singleton-pattern"
    description: "Asegura una instancia única con el patrón Singleton."
    directory: "../singleton"  # Ruta relativa desde src/builder/
    action: "apply"
    variables:
      instance_name: "global-logging-service"
      instance_type: "enterprise"

  # EJEMPLOS DE PASOS DE DESTRUCCIÓN (DESCOMENTAR CON CUIDADO) 
  # - name: "97-cleanup-singleton-pattern"
  #   description: "Limpia la infraestructura del patrón Singleton."
  #   directory: "../singleton" # Ruta relativa desde src/builder/
  #   action: "destroy"

  # - name: "98-cleanup-factory-pattern"
  #   description: "Limpia la infraestructura del patrón Factory."
  #   directory: "../factory"   # Ruta relativa desde src/builder/
  #   action: "destroy"

  # - name: "99-cleanup-builder-pattern"
  #   description: "Limpia la infraestructura del patrón Builder (este mismo módulo)."
  #   directory: "."            # Ruta relativa desde src/builder/
  #   action: "destroy"